# Commons, extensions
x-common: &common
  logging:
    driver: 'json-file'
    options:
      max-size: 32m
      max-file: 3
  restart: 'unless-stopped'

x-local-label: &local
  com.challenge.local.id: 'wchallenge'

version: '3.8'

# Services
services:
  mongo:
    <<: *common
    image: 'mongo:latest'
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - wchallenge
    labels:
      <<: *local

  data-streams:
    <<: *common
    build:
      context: .
      dockerfile: 'docker/DataStreams.Dockerfile'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongo:27017/wchallenge
      NATS_URL: nats://nats:4222
    depends_on:
      - nats
      - mongo
    networks:
      - wchallenge
    labels:
      <<: *local

  worker:
    <<: *common
    build:
      context: .
      dockerfile: 'docker/Worker.Dockerfile'
    environment:
      HUBSPOT_API_KEY: ${HUBSPOT_API_KEY}
      NATS_URL: nats://nats:4222
    depends_on:
      - nats
    networks:
      - wchallenge
    labels:
      <<: *local

  nats:
    <<: *common
    image: nats
    ports:
      - '8222:8222'
      - '4222:4222'
      - '6222:6222'
    networks:
      - wchallenge

# TODO: add transport, i.e. NATS

# Volumes
volumes:
  mongo-data:
    driver: local
    labels:
      <<: *local
  mongo-config:
    driver: local
    labels:
      <<: *local

# Network
networks:
  wchallenge:
    labels:
      <<: *local
